[debug]
# Logging target: "stdout" for console output, "file" for log file + minimal console
log_target = "stdout"

[processing]
# Overlap detection parameters for stitching
# Maximum Y overlap to search when finding image overlap (pixels)
# Setting a max can speed up analysis, if the scans have a consistent overlap
max_y_overlap = 1500

# Minimum confidence score to accept overlap detection (0.0-1.0)
# Lower values are more permissive, higher values require better matches
overlap_confidence_threshold = 0.6

# Backup confidence threshold for low-quality matches (0.0-1.0)
# Used when primary threshold fails but position is consistent
overlap_confidence_backup = 0.4
