# Document Digitizer Configuration File

[debug]
# Save intermediate processing images (a_precrop, b_rotated, c_deskewed, d_stitched)
save_intermediate = true

# Logging target: "stdout" for console output, "file" for log file + minimal console
log_target = "stdout"

[processing]
# Minimum rotation angle (degrees) to trigger deskewing
# Below this threshold, images are considered already straight
angle_threshold = 0.1

# Maximum rotation angle (degrees) to attempt correction
# Larger rotations are likely detection errors and will be skipped
max_rotation = 10.0

# Overlap detection parameters for stitching
# Maximum Y overlap to search when finding image overlap (pixels)
max_y_overlap = 1400

# Maximum X offset to search when aligning images (pixels)  
max_x_offset = 150

# Minimum confidence score to accept overlap detection (0.0-1.0)
# Lower values are more permissive, higher values require better matches
overlap_confidence_threshold = 0.25

# Backup confidence threshold for low-quality matches (0.0-1.0)
# Used when primary threshold fails but position is consistent
overlap_confidence_backup = 0.20

[cropping]
# Pre-processing crop: systematic edge detection
# Maximum percentage of image height to crop from top/bottom edges (0.0-1.0)
precrop_max_vertical_percent = 0.1

# Final crop: edge artifact removal
# Light background threshold (0-255): pixels >= this value considered light background
# Typical document backgrounds are 240-255, adjust lower to be more aggressive
final_crop_light_threshold = 240

# Dark artifact threshold (0-255): pixels <= this value considered dark artifacts  
# Scanning artifacts like #1f1611 (31,22,17) need threshold >= 40
# Adjust higher to catch more subtle dark artifacts
final_crop_dark_threshold = 40

# Minimum percentage of background pixels in column to trigger cropping (0.0-1.0)
# Lower values are more aggressive, higher values more conservative
final_crop_background_percent = 0.05

[output]
# Output image format
# Available: "png" (lossless, recommended), "jpg" (lossy, smaller), "tiff" (lossless, large)
# Recommended: "png" - best balance of quality and file size for documents
file_format = "png"

# Image quality (1-100, only applies to JPG format)
# PNG/TIFF ignore this setting as they are lossless
# Recommended: 95 - high quality with reasonable compression for JPG
quality = 95
